### ISSUE TITLE
[Tracking] Refactor

### ISSUE THREAD

**Issue by JamesxX** [cetz-package/cetz-plot#28]
When implementing logarithmic plots, and then when implementing polar plots, I ran into the challenge that the axis style has no control over how the data is plotted. This make sense if you treat axis styles as a purely visual element, however, this PR turns them into "drivers" that can change more behaviour of the underlying plot.

This is the initial PR, to allow people a better chance at collaborating on the refactor as well as to give maintainers a better chance at reviewing changes in smaller chunks rather than one hefty PR

Firstly, axis styles have been moved out of `axes.typ` (like in a previous draft PR), and instead are located in `plot/axis-styles/`. They become modules which must currently provide 3 functions: `make-ctx` (responsible for constructing the context within which data is prepared), `data-viewport` (responsible for transforming data along any number of axes, and onto the plot itself), and `draw-axes` (responsible for drawing the axes).

`make-ctx` now supplies an array `axes` rather than separately providing `x` and `y`, as a more general solution for when higher dimensional plots are implemented. It must also provide `compute-fill-paths` and `compute-stroke-paths` (previously supplied by the `util.typ` module) to allow for a finer grained control over clipping (of note: path computation occurs PRIOR to data-viewport transformations)

Plot elements (previously `plot.add-<name>()`) are now under `plot.add.<name>`, and `plot.add` has become `plot.add.xy` to disambiguate.

The school-book axis style remains unimplemented but I hope to bring it back at a later stage

### To do and Tracking:

- [ ] Pull current work into `aggressive-refactor` branch (#27)
- [ ] Refactor the refactor: In moving code around a lot, boilerplate code has become prominent. It has been left in this PR because it does not adversely affect the implementation of features, but it is something that will need seeing to as a final step before merging this branch into main
- [ ] Update the manual: Currently failing CI due to having not updated the manual.

#### Axis Styles

Currently tracked are `orthrect-2d` and `polar-2d`. Wanted are: `barycentric-2d`, `polar-3d`, and `orthorect-3d`.

##### Orthorect-2d (previously `scientific` axis style)

- [ ] Reintroduce not drawing unset axes
- [ ] School-book axis style
- [ ] Verify that logarithmic scales are still working

##### Polar-2d (previously `scientific-polar`)

- [ ] Clipping function: The axis style currently relies on the rectangular clipping functions of the orthorect-2d axis style. It leads to unwanted behaviour for epigraphs, among other things
- [ ] Ticks on axes: I think this can be improved stylistically

#### Plot elements

- [x] `add.xy` for plotting continuous/continuous data.
  - [ ] Add thorough tests
- [x] Annotations
- [ ] Bar/Column
- [ ] Boxplot
- [ ] Bubble plot
- [ ] Contour
- [x] Error bar
- [x] Violin plot

There are many more plot elements to introduce too, so if anything needs adding to the list, we should.
